### PR TITLE
Upgrade Ring-Jetty-Adapter to 1.5.0

### PR DESCRIPTION
**Pull request by dpassen**

### CODE REVIEW

**Comment by weavejester** [comment]
Could you change the commit message to:

```
Upgrade Ring-Jetty-Adapter to 1.5.0
```

**Comment by dpassen** [comment]
Yep. Done.

**Comment by dpassen** [comment]
Any chance you can make a release shortly?

**Comment by weavejester** [comment]
Is there a hurry? You know you can override the dependency in your project file, right?

**Comment by dpassen** [comment]
Yes, of course. There's no hurry at all.

**Pull request merged**
